import type { Task } from '@/types/task'

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Setup project architecture',
    description: 'Initialize the base project structure with all required dependencies.',
    status: 'done',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-10',
    createdAt: '2024-01-01T08:00:00Z',
    tags: ['setup', 'architecture'],
  },
  {
    id: '2',
    title: 'Design database schema',
    description: 'Create ERD and finalize the database schema for the application.',
    status: 'done',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-12',
    createdAt: '2024-01-02T09:00:00Z',
    tags: ['database', 'design'],
  },
  {
    id: '3',
    title: 'Implement authentication module',
    description: 'Build login, register, and JWT token management features.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-20',
    createdAt: '2024-01-03T10:00:00Z',
    tags: ['auth', 'security'],
  },
  {
    id: '4',
    title: 'Build dashboard UI',
    description: 'Create the main dashboard with statistics and charts.',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-22',
    createdAt: '2024-01-04T11:00:00Z',
    tags: ['ui', 'dashboard'],
  },
  {
    id: '5',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints using Swagger/OpenAPI.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-25',
    createdAt: '2024-01-05T08:30:00Z',
    tags: ['docs', 'api'],
  },
  {
    id: '6',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated build, test, and deployment.',
    status: 'todo',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-28',
    createdAt: '2024-01-06T09:00:00Z',
    tags: ['devops', 'ci-cd'],
  },
  {
    id: '7',
    title: 'Implement task CRUD operations',
    description: 'Create, read, update, and delete tasks via REST API.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-18',
    createdAt: '2024-01-07T10:00:00Z',
    tags: ['backend', 'api'],
  },
  {
    id: '8',
    title: 'Add unit tests for selectors',
    description: 'Write comprehensive unit tests for all Redux selectors.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-01',
    createdAt: '2024-01-08T11:00:00Z',
    tags: ['testing', 'redux'],
  },
  {
    id: '9',
    title: 'Optimize query performance',
    description: 'Add database indexes and optimize slow queries.',
    status: 'todo',
    priority: 'low',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-05',
    createdAt: '2024-01-09T08:00:00Z',
    tags: ['performance', 'database'],
  },
  {
    id: '10',
    title: 'Design mobile responsive layouts',
    description: 'Ensure all pages work well on mobile and tablet devices.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-08',
    createdAt: '2024-01-10T09:30:00Z',
    tags: ['ui', 'responsive'],
  },
  {
    id: '11',
    title: 'Integrate payment gateway',
    description: 'Connect Stripe API for payment processing.',
    status: 'todo',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-10',
    createdAt: '2024-01-11T10:00:00Z',
    tags: ['payment', 'integration'],
  },
  {
    id: '12',
    title: 'Implement email notifications',
    description: 'Send automated emails for task assignments and due date reminders.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-12',
    createdAt: '2024-01-12T11:00:00Z',
    tags: ['email', 'notifications'],
  },
  {
    id: '13',
    title: 'Add export to CSV feature',
    description: 'Allow users to export task data to CSV format.',
    status: 'todo',
    priority: 'low',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-15',
    createdAt: '2024-01-13T08:00:00Z',
    tags: ['feature', 'export'],
  },
  {
    id: '14',
    title: 'Setup error monitoring',
    description: 'Integrate Sentry for error tracking and monitoring.',
    status: 'done',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-15',
    createdAt: '2024-01-14T09:00:00Z',
    tags: ['monitoring', 'devops'],
  },
  {
    id: '15',
    title: 'Implement search functionality',
    description: 'Add full-text search with debounce for tasks.',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-24',
    createdAt: '2024-01-15T10:00:00Z',
    tags: ['search', 'feature'],
  },
  {
    id: '16',
    title: 'Write E2E tests',
    description: 'Create end-to-end test scenarios using Playwright.',
    status: 'todo',
    priority: 'low',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-20',
    createdAt: '2024-01-16T11:00:00Z',
    tags: ['testing', 'e2e'],
  },
  {
    id: '17',
    title: 'Refactor authentication middleware',
    description: 'Clean up and improve the auth middleware code quality.',
    status: 'todo',
    priority: 'low',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-18',
    createdAt: '2024-01-17T08:30:00Z',
    tags: ['refactor', 'auth'],
  },
  {
    id: '18',
    title: 'Create onboarding tutorial',
    description: 'Build interactive onboarding flow for new users.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-22',
    createdAt: '2024-01-18T09:00:00Z',
    tags: ['ux', 'onboarding'],
  },
  {
    id: '19',
    title: 'Performance audit and optimization',
    description: 'Run Lighthouse audit and optimize Core Web Vitals scores.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-25',
    createdAt: '2024-01-19T10:00:00Z',
    tags: ['performance', 'audit'],
  },
  {
    id: '20',
    title: 'Deploy to production',
    description: 'Final deployment to production environment with zero downtime.',
    status: 'todo',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-03-01',
    createdAt: '2024-01-20T11:00:00Z',
    tags: ['deployment', 'devops'],
  },
  {
    id: '21',
    title: 'User acceptance testing',
    description: 'Coordinate UAT sessions with the product team.',
    status: 'todo',
    priority: 'high',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-02-28',
    createdAt: '2024-01-21T08:00:00Z',
    tags: ['testing', 'uat'],
  },
  {
    id: '22',
    title: 'Add dark mode support',
    description: 'Implement dark/light theme toggle across the application.',
    status: 'done',
    priority: 'low',
    assignee: 'Trần Đình Tài',
    dueDate: '2024-01-16',
    createdAt: '2024-01-22T09:00:00Z',
    tags: ['ui', 'theme'],
  },
]
